### ISSUE TITLE
gRPC Health test

### ISSUE THREAD

**Issue by nefro85** [sygnowski/doer#22]
Health Service Client
https://github.com/grpc/grpc/blob/master/doc/health-checking.md
https://github.com/grpc/grpc/blob/master/src/proto/grpc/health/v1/health.proto
https://github.com/grpc/grpc-java/blob/master/documentation/server-reflection-tutorial.md#enable-server-reflection

**Comment by nefro85** [comment]
Some problem with shadowJar
io.grpc.ManagedChannelRegistry$ProviderNotFoundException: io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider: does not support 1 or more of [class io.grpc.netty.shaded.io.netty.channel.unix.DomainSocketAddress]
        at io.grpc.ManagedChannelRegistry.newChannelBuilder(ManagedChannelRegistry.java:206)
        at io.grpc.ManagedChannelRegistry.newChannelBuilder(ManagedChannelRegistry.java:157)
        at io.grpc.Grpc.newChannelBuilder(Grpc.java:101)
        at io.github.s7i.doer.command.GrpcHealth.grpcHealth(GrpcHealth.java:33)
        at io.github.s7i.doer.command.GrpcHealth.onExecuteCommand(GrpcHealth.java:25)
        at io.github.s7i.doer.command.Command.call(Command.java:18)
        at io.github.s7i.doer.command.Command.call(Command.java:10)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at io.github.s7i.doer.Doer.main(Doer.java:65)
